spring:
  application:
    name: TodoList Backend
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

swagger:
  host:
    url: localhost:8080
    path:

server:
  port: 4567